name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-runner-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on ubuntu runner"
                echo "Runner OS: $RUNNER_OS"
