name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies   
              run: npm cli   

        #0. Checkout the code from the repository
        #1. Install dependencies of our react application
        #2. Execute automated tests