name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "Overwritten workflow"                

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: 'job'

        steps:
            - name: Display information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"            
            - name: Retreive Variable
              run: |
                echo "Variable value: ${{ vars.My_VAR }}"
            - name: print env1 variable
              env:
                MY_OVERWRITTEN_VAR: 'steps'
              run: |
                echo "Workflow env1: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwitten env1: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: print env2 variable
              run: |
                  echo "Workflow env2: ${{ env.MY_JOB_VAR }}"
                  echo "Overwitten env2: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: print env3 variable
              run: |
                  echo "Workflow env3: ${{ env.MY_WORKFLOW_VAR }}"
                  echo "Overwitten env3: ${{ env.MY_OVERWRITTEN_VAR }}"
    echo-data2:
      runs-on: ubuntu-latest
      steps:
        - name: Print Env variable echo data2
          run: |
            echo " Workflow env : $MY_WORKFLOW_VAR "
            echo " Overwritten env: $MY_OVERWRITTEN_VAR"                    
