name: My first workflow
on: 
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  

jobs:
    my-first-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello World"
    my-second-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Bye World"